[general]
import = ["theme.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
opacity = 0.8

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold   = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.0
offset = { x = 0, y = 2 }

